// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: candidate.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CandidateService_CreateCandidate_FullMethodName  = "/voting_proto.CandidateService/CreateCandidate"
	CandidateService_DeleteCandidate_FullMethodName  = "/voting_proto.CandidateService/DeleteCandidate"
	CandidateService_UpdateCandidate_FullMethodName  = "/voting_proto.CandidateService/UpdateCandidate"
	CandidateService_GetByIdCandidate_FullMethodName = "/voting_proto.CandidateService/GetByIdCandidate"
	CandidateService_GetAllCandidates_FullMethodName = "/voting_proto.CandidateService/GetAllCandidates"
)

// CandidateServiceClient is the client API for CandidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandidateServiceClient interface {
	CreateCandidate(ctx context.Context, in *CandidateCreate, opts ...grpc.CallOption) (*Void, error)
	DeleteCandidate(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	UpdateCandidate(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*Void, error)
	GetByIdCandidate(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Candidate, error)
	GetAllCandidates(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllCandidate, error)
}

type candidateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandidateServiceClient(cc grpc.ClientConnInterface) CandidateServiceClient {
	return &candidateServiceClient{cc}
}

func (c *candidateServiceClient) CreateCandidate(ctx context.Context, in *CandidateCreate, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CandidateService_CreateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) DeleteCandidate(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CandidateService_DeleteCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) UpdateCandidate(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CandidateService_UpdateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) GetByIdCandidate(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Candidate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Candidate)
	err := c.cc.Invoke(ctx, CandidateService_GetByIdCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) GetAllCandidates(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*GetAllCandidate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCandidate)
	err := c.cc.Invoke(ctx, CandidateService_GetAllCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateServiceServer is the server API for CandidateService service.
// All implementations must embed UnimplementedCandidateServiceServer
// for forward compatibility
type CandidateServiceServer interface {
	CreateCandidate(context.Context, *CandidateCreate) (*Void, error)
	DeleteCandidate(context.Context, *ById) (*Void, error)
	UpdateCandidate(context.Context, *Candidate) (*Void, error)
	GetByIdCandidate(context.Context, *ById) (*Candidate, error)
	GetAllCandidates(context.Context, *Filter) (*GetAllCandidate, error)
	mustEmbedUnimplementedCandidateServiceServer()
}

// UnimplementedCandidateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCandidateServiceServer struct {
}

func (UnimplementedCandidateServiceServer) CreateCandidate(context.Context, *CandidateCreate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) DeleteCandidate(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) UpdateCandidate(context.Context, *Candidate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) GetByIdCandidate(context.Context, *ById) (*Candidate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) GetAllCandidates(context.Context, *Filter) (*GetAllCandidate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCandidates not implemented")
}
func (UnimplementedCandidateServiceServer) mustEmbedUnimplementedCandidateServiceServer() {}

// UnsafeCandidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandidateServiceServer will
// result in compilation errors.
type UnsafeCandidateServiceServer interface {
	mustEmbedUnimplementedCandidateServiceServer()
}

func RegisterCandidateServiceServer(s grpc.ServiceRegistrar, srv CandidateServiceServer) {
	s.RegisterService(&CandidateService_ServiceDesc, srv)
}

func _CandidateService_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CandidateCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_CreateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, req.(*CandidateCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_DeleteCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).DeleteCandidate(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_UpdateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Candidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).UpdateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_UpdateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).UpdateCandidate(ctx, req.(*Candidate))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_GetByIdCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetByIdCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_GetByIdCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetByIdCandidate(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_GetAllCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetAllCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_GetAllCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetAllCandidates(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

// CandidateService_ServiceDesc is the grpc.ServiceDesc for CandidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voting_proto.CandidateService",
	HandlerType: (*CandidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCandidate",
			Handler:    _CandidateService_CreateCandidate_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _CandidateService_DeleteCandidate_Handler,
		},
		{
			MethodName: "UpdateCandidate",
			Handler:    _CandidateService_UpdateCandidate_Handler,
		},
		{
			MethodName: "GetByIdCandidate",
			Handler:    _CandidateService_GetByIdCandidate_Handler,
		},
		{
			MethodName: "GetAllCandidates",
			Handler:    _CandidateService_GetAllCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "candidate.proto",
}
